-  xdemocomponent:
    platform: "posix"
    command: "/sbin/ifconfig"
    autostart: true
    observer:
      - stdout:
          maxwaittime: 5
          criteria: "eth0"
    errorpolicy: "strict"
    description: "ifconfig configures a network interface"