-  xdemocomponent:
    platform: "posix"
    command: "/sbin/ifconfig"
    autostart: true
    observer:
      stdout:
        maxwaittime: 2
        criteria: "This must be found in the STDOUT"
      stdoutexclude:
        criteria: "This must be NOT found in the STDOUT"
    errorpolicy: "strict"
    description: "ifconfig configures a network interface"