-  xdemocomponent:
    platform: "posix"
    autostart: true
    exitallowed: true
    initcriteria:
      - stdout:
          maxwaittime: 1
          criteria: "eth0"
    initpolicy: "strict"
    description: "ifconfig configures a network interface"